### ISSUE TITLE
Organism life cycle stage and sample timing

### ISSUE THREAD

**Issue by CecSve** [gbif/doc-freshwater-data-publishing-guide#14]
Feedback for: https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#life-cycle-stage

> Life stage details provide similarly valuable information about population dynamics for other [organism groups](https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#organism-group), (...)

I propose the dwc:lifeStage term is included here:

> Life stage **([dwc:lifeStage](https://dwc.tdwg.org/terms/#dwciri:lifeStage))** details provide similarly valuable information about population dynamics for other [organism groups](https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#organism-group), (...)

Please also consider that GBIF has [a controlled vocabulary for life stage](https://registry.gbif.org/vocabulary/LifeStage) and it seems some of the concepts mentioned in the text is currently not supported by the concepts (fish-related life stages). This means that the values provided that do not match a concept are not interpreted and not searchable in GBIF. 

If concepts are missing in the vocabulary, please propose them [here](https://github.com/gbif/vocabulary/issues/119) - ideally referring to an external source controlled vocabulary.

@ManonGros may have further comments

**Comment by jenlento** [comment]
@CecSve Thank you for drawing our attention to this controlled list. We will update the examples in the table to match the controlled vocabulary. As noted in an earlier comment, we do not have reference to specific DwC terms in the introduction section (section 1) as this is a background section. The terms are explained in later sections. We believe it would overly complicate the guide to include reference to the terms in the text.

@kcopas in Table 7, column Examples, row lifeStage, please change the text to read: 
"One of egg, larva, pupa, adult, subadult, juvenile, nymph, immature, nauplius"
We also need an addition to the text. In section 2.2, 4th paragraph, after the sentence, "Additional fields for observation data include the sex and life stage, both of which are conditional based on the organism group (for example, sex can be determined and is relevant for fish, mammals, birds, and decapods; life stage can be determined and is relevant for copepods, benthic macroinvertebrates, fish and birds)." can you please add the sentence, "The DwC term lifeStage has a controlled vocabulary (see https://registry.gbif.org/vocabulary/LifeStage/concepts for full list), and this vocabulary does not include all terms that are relevant for freshwater. For example, young of year is not part of the controlled vocabulary, and it is recommended that juvenile be used instead. Similarly, juvenile can be used instead of copepodite, and immature can be used instead of early instar."

**Comment by jenlento** [comment]
Change made
