### ISSUE TITLE
Organism groups

### ISSUE THREAD

**Issue by CecSve** [gbif/doc-freshwater-data-publishing-guide#16]
Feedback for: https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#organism-groups

> [Table 1](https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#table-01) outlines the organism groups that we recommend adding to freshwater records in GBIF.

Please provide examples how organism groups should be shared with GBIF by providing specific fields in which the data can be shared.

It is unclear from the paragraph whether such data can be shared for all dataset classes, which I do not think is currently possible. 

> Adding the organism group to which an observation belongs is a way to make data easier to find and select within GBIF.

This statement sound like the information should be added at occurrence record level, however, there is currently no dwc/gbif term that can be used to add such data. I realise that there is a [proposal](https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/index.en.html#freshwater-dwc-extension-terms) for an extension to capture the currently uncapturable data, but I don't think the need for many of these terms are freshwater specific (for example [biome](https://github.com/tdwg/dwc/issues/38)). 

@ManonGros may have further comments

**Comment by jenlento** [comment]
> Please provide examples how organism groups should be shared with GBIF by providing specific fields in which the data can be shared.
As noted in earlier comments, we prefer that this is done later in the document when the fields are described. However, we did notice that we missed this information in our description.

> It is unclear from the paragraph whether such data can be shared for all dataset classes, which I do not think is currently possible.
Information on organism group can be provided for all data classes. Resources metadata could indicate which organism group the data describe (i.e., indicating that it's a dataset of fish observations), Checklist datasets could similarly indicate which organism groups are included in the checklist. It is necessary that this information be included in Occurrence datasets and Sampling event datasets for users to be able to find and analyze datasets that correspond to the organism group with which they are working.

@kcopas In Section 2.2, after the sentence, "The freshwater amendments include general fields describing the site where the observation was made, such as the water body name, a description of the location and the elevation (Table 7).", please add the following text: "The organism group should be included for all GBIF data classes (link to section on data classes). This information is not currently captured in existing DwC terms. It is recommended that the term freshwaterOrganismGroup be defined in a freshwater extension of DwC so that it can be a searchable term in GBIF (link to section 3.1.1), but until the creation of that extension, this information should be included in the dynamicProperties term (e.g., as organism group:fish)."
In Section 3.1.1 under the term freshwaterOrganismGroup, under inclusion, please add Checklist.

**Comment by jenlento** [comment]
Change made
