### ISSUE TITLE
data vs. dataset classes

### ISSUE THREAD

**Issue by dschigel** [gbif/doc-freshwater-data-publishing-guide#19]
Spotted that language in the title https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#gbif-data-classes is different from https://www.gbif.org/dataset-classes. I would think that GBIF's prevails @kcopas? If confirmed, whole doc must be checked for terms consistency.

Additional thought
A chance to think about completeness of https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#glossary, too. Which and how many GBIF terms would be alien / new to freshwater community? In the absence of master glossary at GBIF, linking out is not really an option. From training experience, even the most basic terms in GBIF can confuse / alienate, e.g. occurrence, dataset. Common sense to apply how many of this need explanations.

**Comment by jenlento** [comment]
Thank you for catching the inconsistency in the use of "data classes" vs "dataset classes". We have corrected these to all say "dataset classes".

With respect to the additional glossary terms, we were instructed not to include the more general GBIF terms because having definitions for the same terms in multiple places on the website becomes problematic if changes need to be made to definitions. Therefore, we have restricted our glossary to terms new to this guide.
