### ISSUE TITLE
Checklist datasets

### ISSUE THREAD

**Issue by CecSve** [gbif/doc-freshwater-data-publishing-guide#23]
Feedback for: https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/#checklist-datasets

> Checklist data are not specific to a location and do not represent individual observations.

This statement is not technically correct and should instead be phrased like this:

> Checklist data are not **necessarily** specific to a location and do not **always** represent individual observations. **However, they can be location specific (like the country-specific [Global Register of Introduced and Invasive Species (GRIIS) checklists](https://www.gbif.org/dataset/search?publishing_org=cdef28b1-db4e-4c58-aa71-3c5238c2d0b5)) and may contain occurrences ([example](https://www.gbif.org/dataset/6baf6a53-c106-40fb-bbde-f6d4e4051513)).**

Please also refer to the appropriate extension for checklist core datasets, such as the [distribution extension](https://rs.gbif.org/extension/gbif/1.0/distribution_2022-02-02.xml) and the [species profile extension](https://rs.gbif.org/extension/gbif/1.0/speciesprofile_2019-01-29.xml) (look for keyword = dwc:Taxon for extensions that can be used with taxon core datasets).

@ManonGros you may have more input here

**Comment by ManonGros** [comment]
Generally, the guide is a bit dismissive of the checklists. I think that a lot of the information that is encouraged to be shared (for example the habitat for a given species/life stage) is actually something that could be shared in checklists rather than occurrences.
In fact, I would argue that a lot of what we are missing is species information. Having a good comprehensive checklist of freshwater species would help make freshwater data more accessible to users. As mentioned above, the checklist extensions can be used to share a lot of species information.

**Comment by jenlento** [comment]
@CecSve Thank you for the suggestions. We have made the changes.

@ManonGros We have adjusted the text to be less dismissive of checklist data. However, we feel that the fields we've specified should be included with occurrence data would not be compatible with checklist data due to the plasticity of freshwater species characteristics. For example, most freshwater insects also have a terrestrial life stage (i.e., will be found in different habitats depending on their age/lifestage), some fish spend time in both freshwater and marine habitats, some plants can live in or near water. etc. These are not characteristics that can be generalized to the species. In freshwater analysis, the location of observation is equally as important as the species checklist.
