### ISSUE TITLE
Organism groups

### ISSUE THREAD

**Issue by MattBlissett** [gbif/doc-freshwater-data-publishing-guide#27]
Feedback on https://docs.gbif-uat.org/freshwater-data-publishing-guide/en/index.en.html#organism-groups

> Adding the organism group to which an observation belongs is a way to make data easier to find and select within GBIF. For example, someone who is interested in phytoplankton diversity would find it useful to be able to select data by the organism group name (phytoplankton) rather than having to search separately for the taxonomic classes that are part of this assemblage. 

This is not true, as it would need additional development to add a new search term. 

It also seems like something we should apply using the taxon, rather than expecting every occurrence to know what organism group to use. 

> if each of the taxa of interest (reaching from class to orders) were amended with the organism group name

I think that's supposed to be "annotated" or something similar.

**Comment by ManonGros** [comment]
See also: https://github.com/gbif/doc-freshwater-data-publishing-guide/issues/16

**Comment by ManonGros** [comment]
The concept of organism group seems rather impractical for occurrences: these correspond to a combination of taxa/life stage. I agree that it is something that should be applied to taxa, not occurrences.

Perhaps the guide should provide guidelines and encourage checklist publishing instead: https://github.com/gbif/doc-freshwater-data-publishing-guide/issues/23

**Comment by jenlento** [comment]
We have changed "amended" to "annotated" as suggested.

With respect to the issue of organism groups, this is one of the biggest issues limiting the use of freshwater biodiversity data from GBIF in large-scale meta-analyses, because the work that would be necessary to find all relevant taxa from within an organism group (which is usually the level at which freshwater researchers are working - i.e., at the level of fish assemblages, benthic macroinvertebrate assemblages, algal assemblages, macrophyte assemblages, phytoplankton assemblages, zooplankton assemblages, etc.) is daunting and often difficult to do without missing some taxa. Annotating the data with the organism group is a simple and effective way to support the effective use of GBIF data, and it would likely lead to more freshwater scientists appreciating the utility of GBIF and being more ready to supply data and make use of data from GBIF.
