### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by MattBlissett** [gbif/doc-freshwater-data-publishing-guide#4]
Just some comments as I look at the table formatting.

> "LivingSpecimen" refers to observations of living organisms that were not collected (e.g., catch and release or point count).

No, a living specimen is a specimen that is alive, for example in a zoo or botanical garden.

Catch and release or point counts are HumanObservations.

> Not permitted are, i.e., working names ("Adicella sp.4"), common names ("creamy caddisfly"), or names containing identification qualifiers ("Adicella cf. cremisa").

Several uses of "i.e." (_id est_, "that is") when it should be "e.g.".

> Use the following format: yyyy-mm-dd four-digit year-month-day. Please make sure to provide separate columns for year, month and day as well

Doesn't matter, so long as if both eventDate and year/month/day are provided they are consistent.

> Note that the time should not be included as part of this element, please use eventTime instead where required

This isn't a restriction for DWC or GBIF, why add it here?

> For freshwater data, best practice is that coordinates are mandatory, although the GBIF data description indicates that this can be coarse (e.g., country).

I think add "in which case ensure the coordinateUncertaintyInMeters is set accordingly".  But I'm not sure what the "GBIF data description" is, and I don't think we should encourage adding centroid coordinates just for the sake of it.

> For example, it is recommended that data providers include year, month and day as separate columns in their data. This avoids ambiguities that might occur due to regional differences in how year, month, and day are combined into a single field (i.e. confusion of month and day).

This isn't specific to freshwater. (And yyyy-mm-dd in eventDate is sufficient.)

> dynamicProperties

Comment says to use JSON, but the example is not JSON:

```json
{
"biome":"river",
"ecosystem functional group":"lowland river",
"microhabitat":"sand",
"data category":"opportunistic observation",
"type of contribution":"community-based research data",
"organism group":"fish"
}
```

> found dead outside of the water

That particular information belongs in dwc:vitality, at least the "dead" bit.

> The extension

Some of these are more general than freshwater.

**Comment by kcopas** [comment]
The "i.e." to "e.g." transformation is complete. I had started this but clearly neglected to fix the second section where it occurred the most—thanks @MattBlissett !

**Comment by kcopas** [comment]
#4 Jen: maybe we should go through these comments together.

There are two comments under this issue stating that date format doesn't matter and separate columns are not needed: I know both Astrid and I feel very strongly about this text due to years of experience dealing with messy date data. If you've ever had to compile data from different sources, you know how often dates are a disaster (even within the same data file!) with day, month, and sometimes even year flipped around and difficult to distinguish. I even found an issue with this when I randomly selected a freshwater dataset on GBIF to download, so GBIF is not immune and we need to urge users to be more careful in how they set up their dates.

**Comment by jenlento** [comment]
> No, a living specimen is a specimen that is alive, for example in a zoo or botanical garden.
> Catch and release or point counts are HumanObservations.

We weren't 100% sure about LivingSpecimen, so this can be edited as described. 

> Doesn't matter, so long as if both eventDate and year/month/day are provided they are consistent.

As noted in my comment, I still feel strongly about date data :-)

> This isn't a restriction for DWC or GBIF, why add it here?

For eventTime, we weren't suggesting that it was required, just that any time information that is provided should be added to eventTime, not to date. If the text needs to be changed to make this clear, we can do that. The key thing here was that time ideally shouldn't be part of the eventDate

> I think add "in which case ensure the coordinateUncertaintyInMeters is set accordingly". But I'm not sure what the "GBIF data description" is, and I don't think we should encourage adding centroid coordinates just for the sake of it.

The suggestion for coordinates is fine. By "GBIF description" we meant the text on GBIF that indicates what information is necessary for Occurrence data vs Event data (the website notes that Occurrence data can have coarse geographic information). 

> Comment says to use JSON, but the example is not JSON:

The text says "such as JSON" which doesn't mean that it MUST be JSON, only that it is an option. The examples that have been provided are freshwater-specific.

> That particular information belongs in dwc:vitality, at least the "dead" bit.

The point here is to indicate that it's a freshwater specimen that was found outside the water (the dead part is not important). So this text could be changed to "Found outside of the water on the shoreline" or something similar.

> Some of these are more general than freshwater.

That's definitely true, but the goal is here to indicate what is really needed for freshwater. Although many can apply to different data, they are important for freshwater and that's why it is best practice to include them with freshwater data.

**Comment by schmikloi** [comment]
some additional thoughts of mine (if there are none, I agree with Jen)

> > No, a living specimen is a specimen that is alive, for example in a zoo or botanical garden.
> > Catch and release or point counts are HumanObservations.
> 
> We weren't 100% sure about LivingSpecimen, so this can be edited as described.

means we need to change the example as well; from LivingSpecimen to HumanObservation; correct @jenlento ?

and in the comment: "HumanObservation" refers to observations of living organisms that were not collected (e.g. catch and release or point count).
correct @jenlento ?


> > Doesn't matter, so long as if both eventDate and year/month/day are provided they are consistent.
> 
> As noted in my comment, I still feel strongly about date data :-)

me too!


> > This isn't a restriction for DWC or GBIF, why add it here?
> 
> For eventTime, we weren't suggesting that it was required, just that any time information that is provided should be added to eventTime, not to date. If the text needs to be changed to make this clear, we can do that. The key thing here was that time ideally shouldn't be part of the eventDate

we could say "use the field eventTime"


> > I think add "in which case ensure the coordinateUncertaintyInMeters is set accordingly". But I'm not sure what the "GBIF data description" is, and I don't think we should encourage adding centroid coordinates just for the sake of it.
> 
> The suggestion for coordinates is fine. By "GBIF description" we meant the text on GBIF that indicates what information is necessary for Occurrence data vs Event data (the website notes that Occurrence data can have coarse geographic information).
> 
> > Comment says to use JSON, but the example is not JSON:
> 
> The text says "such as JSON" which doesn't mean that it MUST be JSON, only that it is an option. The examples that have been provided are freshwater-specific.
> 
> > That particular information belongs in dwc:vitality, at least the "dead" bit.
> 
> The point here is to indicate that it's a freshwater specimen that was found outside the water (the dead part is not important). So this text could be changed to "Found outside of the water on the shoreline" or something similar.

I agree, just Found with a small f ;-)...

 
> > Some of these are more general than freshwater.
> 
> That's definitely true, but the goal is here to indicate what is really needed for freshwater. Although many can apply to different data, they are important for freshwater and that's why it is best practice to include them with freshwater data.

**Comment by MattBlissett** [comment]
I'm reopening this as the LivingSpecimen definition has not been corrected.

**Comment by kcopas** [comment]
[like]  Kyle Copas reacted to your message:
________________________________

**Comment by jenlento** [comment]
@kcopas In Table 5, please make the following changes:
In the column Examples, please replace "LivingSpecimen" with "HumanObservation" 
And in the column Comment, where the text says, ""LivingSpecimen" refers to observations of living organisms that were not collected (e.g. catch and release or point count)." please replace "Living Specimen" with "HumanObservation"

**Comment by kcopas** [comment]
@jenlento just to be clear, you and @schmikloi both have permissions to make edits on the document—it is not an exclusive power I hold. If there are any that are technically challenging or do require my help, I'm happy to help, but it's best not to devolve simple ones to me, given my other commitments.

Meanwhile, your detailed responses are precisely what we like to see come out of this process, as it documents authorial choices regardless of whether you accept gist of the comments, take a pass on them or somewhere in between. Thanks for that.

**Comment by jenlento** [comment]
Change made.
